[queue]
addr="amqp://admin:admin@192.168.99.101:5672/"
logFilePath="D:/juest/src/orp/logs/queue/monitor.log"
exchange="test.direct"
[[queue.work]]
name="orderQueue"#队列名称
enable=true
maxIdle=10
[[queue.work]]
name="testQueue"#队列名称
enable=true
maxIdle=11
[[queue.work]]
name="orderTransformQueue"#队列名称
enable=true
maxIdle=2
[logger]
FileName = "D:/juest/src/orp/logs"
FileNameFormat = ".%Y%m%d"
WithRotationTime = 1
LogFileExpired = 1
ReportCaller= true
ShowConsole= false
Level= "debug"
AppName= "queue"
