[app]
serviceName = "AutoIdService"
port = 8191
centerId = "127.0.0.1:8500"
[autoid]
    [autoid.master]
    dsn = "root:root@tcp(127.0.0.1:3306)/db_auto_id_master?charset=latin1&interpolateParams=true"
    autoIdType="res"
    autoIdTable="res"
    active = 1
    idle = 1
    idleTimeout = "1m"
    [[autoid.slave]]
    dsn = "root:root@tcp(127.0.0.1:3306)/db_auto_id_slave?charset=latin1&interpolateParams=true"
    autoIdType="slave"
    autoIdTable="res_slave_current_0"
    active = 1
    idle = 1
    idleTimeout = "1m"
    capacity=["default:1000","1005:999"]
    weight=100
    maxRetry=2
    [[autoid.slave]]
    dsn = "root:root@tcp(127.0.0.1:3306)/db_auto_id_slave?charset=latin1&interpolateParams=true"
    autoIdType="slave"
    autoIdTable="res_slave_current_1"
    active = 1
    idle = 1
    idleTimeout = "1m"
    capacity=["default:1000","1010:999"]
    weight=50
    maxRetry=2
    [[autoid.slave]]
    dsn = "root:root@tcp(127.0.0.1:3306)/db_auto_id_slave?charset=latin1&interpolateParams=true"
    autoIdType="slave"
    autoIdTable="res_slave_current_2"
    active = 1
    idle = 1
    idleTimeout = "1m"
    capacity=["default:1000","1010:999"]
    weight=50
    maxRetry=2
    [[autoid.slave]]
    dsn = "root:root@tcp(127.0.0.1:3306)/db_auto_id_slave?charset=latin1&interpolateParams=true"
    autoIdType="slave"
    autoIdTable="res_slave_current_3"
    active = 1
    idle = 1
    idleTimeout = "1m"
    capacity=["default:1000","1010:999"]
    weight=50
    maxRetry=2
    [[autoid.slave]]
    dsn = "root:root@tcp(127.0.0.1:3306)/db_auto_id_slave?charset=latin1&interpolateParams=true"
    autoIdType="slave"
    autoIdTable="res_slave_current_4"
    active = 1
    idle = 1
    idleTimeout = "1m"
    capacity=["default:1000","1010:999"]
    weight=50
    maxRetry=2
    [[autoid.slave]]
    dsn = "root:root@tcp(127.0.0.1:3306)/db_auto_id_slave?charset=latin1&interpolateParams=true"
    autoIdType="slave"
    autoIdTable="res_slave_current_5"
    active = 1
    idle = 1
    idleTimeout = "1m"
    capacity=["default:1000","1010:999"]
    weight=50
    maxRetry=2
    [[autoid.slave]]
    dsn = "root:root@tcp(127.0.0.1:3306)/db_auto_id_slave?charset=latin1&interpolateParams=true"
    autoIdType="slave"
    autoIdTable="res_slave_current_6"
    active = 1
    idle = 1
    idleTimeout = "1m"
    capacity=["default:1000","1010:999"]
    weight=50
    maxRetry=2
    [[autoid.slave]]
    dsn = "root:root@tcp(127.0.0.1:3306)/db_auto_id_slave?charset=latin1&interpolateParams=true"
    autoIdType="slave"
    autoIdTable="res_slave_current_7"
    active = 1
    idle = 1
    idleTimeout = "1m"
    capacity=["default:1000","1010:999"]
    weight=50
    maxRetry=2
    [[autoid.slave]]
    dsn = "root:root@tcp(127.0.0.1:3306)/db_auto_id_slave?charset=latin1&interpolateParams=true"
    autoIdType="slave"
    autoIdTable="res_slave_current_8"
    active = 1
    idle = 1
    idleTimeout = "1m"
    capacity=["default:1000","1010:999"]
    weight=50
    maxRetry=2
    [[autoid.slave]]
    dsn = "root:root@tcp(127.0.0.1:3306)/db_auto_id_slave?charset=latin1&interpolateParams=true"
    autoIdType="slave"
    autoIdTable="res_slave_current_9"
    active = 1
    idle = 1
    idleTimeout = "1m"
    capacity=["default:1000","1010:999"]
    weight=50
    maxRetry=2
