[app]
serviceName = "AutoIdV2Service"
port = 8194
centerId = "localhost:8500"
[autoid]
        capacity=4000
        len=7
    [autoid.db]
        dsn = "root:root@tcp(localhost:3306)/db_auto_id_master?charset=latin1&interpolateParams=true"
        autoIdTable="res"
        active = 1
        idle = 1
        idleTimeout = "1m"
